name: CI - deploy
on:
  push:
    branches:
      - main
    paths:
      - "*.lock"
      - "*.ts"
      - "*.js"
      - "*.json"
      - "contracts/*"
      - "test/*"
  pull_request:
    paths:
      - "!*.MD"
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: ["18"]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    env:
      # These are just dummy values to prevent hardhat complaining about config issues
      SONIC_BLAZE_RPC: NA
      SONIC_RPC: NA
      PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: yarn deploy:vrf
